version: "3"
services:
  todo-api:
    build: ./backend
    environment:
      MYSQL_STORAGE: mysql
      MYSQL_HOST: db
      MYSQL_USER: ${DB_USR}
      MYSQL_PWD: ${DB_PW}
      MYSQL_DB: ${DB_DATABASE}
    labels:
      - "traefik.http.routers.todo-api.rule=Host(`s140013.devops-ap.be`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo-api.tls=true"
      - "traefik.http.services.todo-api.loadbalancer.server.port=3000"
      - "traefik.http.routers.todo-api.tls.certresolver=letsencrypt"
    networks:
      - proxy
      - database

  frontend:
    image: nginx:1.22
    volumes:
      - "./frontend:/usr/share/nginx/html/"
    labels:
      - "traefik.http.routers.frontend.rule=Host(`s140013.devops-ap.be`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
    networks:
      - proxy

  db:
    image: mysql:8.2.0
    volumes:
      - "db-volume:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USR}"
      - "MYSQL_PASSWORD=${DB_PW}"
    networks:
      - database

volumes:
  db-volume:


networks:
  proxy:
    external: true
    name: traefik
  database:
